### ISSUE TITLE
[BUG] Game crashes when trying to use water bucket on barrier in 1.20.1.

### ISSUE THREAD

**Issue by LittleCircleOO** [eclipseisoffline/eclipsestweakeroo#1]
**Describe the bug**
Since waterlogged barriers were just added in 1.20.2, the [mixin here](https://github.com/eclipseisoffline/eclipsestweakeroo/blob/1.20.1/src/main/java/xyz/eclipseisoffline/eclipsestweakeroo/mixin/BarrierBlockMixin.java) causes the game to crash when the player tries to make the barrier waterlogged in 1.20.1

**To Reproduce**
1. Install this mod (0.4.5) on 1.20.1.
2. Try to make the barrier waterlogged.

**Expected behavior**
The game won't crash.

**Screenshots/logs**
```
java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:barrier}
	at MC//net.minecraft.state.State.get(State.java:98)
	at MC//net.minecraft.block.Waterloggable.tryFillWithFluid(Waterloggable.java:25)
	at MC//net.minecraft.item.BucketItem.placeFluid(BucketItem.java:139)
	at MC//net.minecraft.item.BucketItem.use(BucketItem.java:80)
	at MC//net.minecraft.item.ItemStack.use(ItemStack.java:284)
	at MC//net.minecraft.client.network.ClientPlayerInteractionManager.method_41929(ClientPlayerInteractionManager.java:387)
	at MC//net.minecraft.client.network.ClientPlayerInteractionManager.sendSequencedPacket(ClientPlayerInteractionManager.java:278)
	at MC//net.minecraft.client.network.ClientPlayerInteractionManager.interactItem(ClientPlayerInteractionManager.java:379)
	at MC//net.minecraft.client.MinecraftClient.doItemUse(MinecraftClient.java:1822)
	at MC//net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient.java:2052)
	at MC//net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1883)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.3/java.lang.reflect.Method.invoke(Method.java:568)
	at app//oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at app//oolloo.jlw.Wrapper.main(Wrapper.java:51)
```

**Minecraft setup (please complete the following information):**
- Minecraft version: 1.20.1
- Fabric loader version: 0.15.11
- Eclipse's Tweakeroo Additions version 0.4.5
- Tweakeroo version  0.17.1
- Malilib version 0.16.3

**Comment by eclipseisoffline** [comment]
This issue has been resolved in the latest version for 1.20.1 (0.6.5).
